
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "fbarrera",
    "password" : "fredy123",
    "email": "fredy@email.com",
    "name": "Fredy Barrera"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "Jamorera",
    "password" : "jmorera12345"
   
}