
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "jsmorera",
    "password" : "j12345",
    "email": "johnm@email.com",
    "name": "John A Morera"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "jsmorera",
    "password" : "j12345"
   
}