
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "Jmorera",
    "password" : "SW5nZTA5MjU=",
    "email": "johnmorera@email.com",
    "name": "John Morera Barrera"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "Jmorera",
    "password" : "SW5nZTA5MjU="
   
}