###
GET http://localhost:8080/api/users
Authorization: Bearer JWT

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "amorera",
    "password": "amorera12345",
    "email": "a@email.com",
    "name": "John Morera",
    "roles":[
        "admin",
        "user"
    ]
}

###
PUT http://localhost:8080/api/users/jmorera
Content-Type: application/json

{
    "username": "jmorera",
    "email": "john@email.com",
    "name": "John Morera",
    "roles":[
        "admin",
        "user"
    ]

}

###

PATCH http://localhost:8080/api/users/jmorera/active

###

PATCH http://localhost:8080/api/users/jmorera/deactive


